name: flowmoney
description: FlowMoney - Smart Money Tracking App for Android & iOS
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  sqflite: ^2.3.3
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  fl_chart: ^0.69.0
  flutter_local_notifications: ^17.2.4
  share_plus: ^10.0.0
  intl: ^0.19.0
  csv: ^6.0.0
  excel: ^4.0.6
  uuid: ^4.4.2
  path: ^1.9.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
